TOKENS = [
    ("programa", "programainicio"),
    ("programa", "execucaoinicio"),
    ("programa", "fimexecucao"),
    ("programa", "fimprograma"),
    ("declaracao", "definainstrucao"),
    ("declaracao", "como"),
    ("bloco", "inicio"),
    ("bloco", "fim"),
    ("iteracao", "repita"),
    ("iteracao", "vezes"),
    ("iteracao", "fimrepita"),
    ("laco", "enquanto"),
    ("laco", "faca"),
    ("laco", "fimpara"),
    ("condicional", "se"),
    ("condicional", "entao"),
    ("condicional", "fimse"),
    ("condicional", "senao"),
    ("condicional", "fimsenao"),
    ("instrucao", "mova"),
    ("instrucao", "passos"),
    ("instrucao", "vire para"),
    ("instrucao", "pare"),
    ("instrucao", "finalize"),
    ("instrucao", "apague lampada"),
    ("instrucao", "acenda lampada"),
    ("instrucao", "aguarde ate"),
    ("condicao", "robo pronto"),
    ("condicao", "robo ocupado"),
    ("condicao", "robo parado"),
    ("condicao", "robo movimentado"),
    ("condicao", "frente robo bloqueada"),
    ("condicao", "dirieta robo bloqueada"),
    ("condicao", "esquerda robo bloqueada"),
    ("condicao", "lampada acessa a grente"),
    ("condicao", "lampada acessa a esquerda"),
    ("condicao", "lampada acessa a direita"),
    ("condicao", "lampada apagada a frente"),
    ("condicao", "lampada apagada a esquerda"),
    ("condicao", "lampada apagada a direita"),
    ("sentido", "esquerda"),
    ("sentido", "direita"),
]

print(TOKENS)